<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Optimize>true</Optimize>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="IsExternalInit.cs" />
    <Reference Include="Lua">
      <HintPath>D:\Git\CoreAI\Assets\CoreAIMods\Plugins\Lua.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Bcl.TimeProvider">
      <HintPath>D:\Git\CoreAI\Assets\Packages\Microsoft.Bcl.TimeProvider.10.0.9\lib\netstandard2.0\Microsoft.Bcl.TimeProvider.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>C:\Program Files\Unity\Hub\Editor\6000.3.14f1\Editor\Data\NetStandard\EditorExtensions\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
